version: "3.8"
services:
    api_invoice:
        container_name: api_invoice
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 9000:8080
        depends_on:
            - database-invoice
    database-invoice:
        container_name: database-invoice
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - db-invoice:/var/lib/postgresql/data
    pgadmin-invoice:
        image: dpage/pgadmin4
        container_name: pgAdmin-invoice
        ports:
          - "5060:80"
        depends_on:
          - database-invoice 
        environment:
          PGADMIN_DEFAULT_EMAIL: omaressamhegazy6@gmail.com
          PGADMIN_DEFAULT_PASSWORD: password 
volumes:
    db-invoice: ~
